app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/post/{id}',['as'=>'home.post','uses'=>'AdminPostsController@post']);

Route::resource('admin/users','AdminUsersController');

Route::get('/admin',function (){
    return view('admin.index');
});

Route::get('/admin/create','AdminUsersController@create');

Route::group(['middleware'=>'admin'],function (){
    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCategoriesController');
    Route::resource('admin/media','AdminMediaController');
    //Route::resource('admin/media/store','AdminMediaController@store');
   // Route::get('admin/media/upload',['as'=>'admin.media.upload']);

    Route::resource('admin/comments','PostCommentsController');
    Route::resource('admin/comments/replies','CommentRepliesController');
});

Route::group(['middleware'=>'auth'],function (){
    Route::post('comment/reply','CommentRepliesController@createReply');
});

app/Post.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use Sluggable;
    use SluggableScopeHelpers;
    
    //

    protected $fillable = [
        'user_id',
        'category_id',
        'photo_id',
        'title',
        'body',
    ];

  
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        // TODO: Implement sluggable() method.
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Create Posts</h1>

    {!! Form::open(['method'=>'POST','action'=>'AdminPostsController@store','files'=>'true']) !!}
    <div class="form-group">
        {!! Form::label('title','Title :') !!}
        {!! Form::text('title',null,['class'=>'form-control','rows'=>3]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('body','Body :') !!}
        {!! Form::textarea('body',null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('category_id','Category ') !!}
        {!! Form::select('category_id',[0=>'select']+$categories,null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('photo_id','File:') !!}
        {!! Form::file('photo_id',null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::submit('Create Post',['class'=>'btn btn-primary']) !!}
    </div>
    {!! Form::close() !!}
    @include('includes.form_error')
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Edit Posts</h1>

    <div class="col-sm-3">
        <img src="{{$post->photo ? $post->photo->file : '/images/default.png'}}" alt="" class="img-responsive img-rounded" />
    </div>
    <div class="col-sm-9">
    {!! Form::model($post,['method'=>'PATCH','action'=>['AdminPostsController@update',$post->id],'files'=>'true']) !!}
    <div class="form-group">
        {!! Form::label('title','Title :') !!}
        {!! Form::text('title',null,['class'=>'form-control','rows'=>3]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('body','Body :') !!}
        {!! Form::textarea('body',null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('category_id','Category ') !!}
        {!! Form::select('category_id',[0=>'select']+$categories,null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('photo_id','File:') !!}
        {!! Form::file('photo_id',null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::submit('Create Post',['class'=>'btn btn-primary']) !!}
    </div>
    {!! Form::close() !!}
    <div class="row text-center">
        {!! Form::open(['method'=>'DELETE','action'=>['AdminPostsController@destroy',$post->id]]) !!}
        {!! Form::submit('Delete Post',['class'=>'btn btn-danger']) !!}
        {!! Form::close() !!}
    </div>
    </div>
    @include('includes.form_error')


@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

    @section('content')
    <h1>Posts</h1>
    @if(Session::has('deleted_post'))
        <p class="bg bg-danger">{{session('deleted_user')}}</p>
    @endif
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Photo</th>
                <th>Title</th>
                <th>Body</th>
                <th>Category</th>
                <th>Photo</th>
                <th>Author</th>
                <th>Created at</th>
                <td>Updated at</td>
            </tr>
            </thead>
            <tbody>
            @if($posts)
                @foreach($posts as $post)
                    <tr>
                        <td>{{$post->id}}</td>
                        <td><img height="50" src="{{$post->photo ? $post->photo->file : "/images/default.png"}}" alt=""></td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->body}}</td>
                        <td>{{$post->category ? $post->category->name : 'No category'}}</td>
                        <td><a href="{{route('home.post',$post->slug)}}">View Post</a></td>
                        <td><a href="{{route('admin.comments.show',$post->id)}}">View Comments</a></td>
                        <td>{{$post->created_at->diffForHumans()}}</td>
                        <td>{{$post->updated_at->diffForHumans()}}</td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-5">
            {{$posts->render()}}
        </div>
    </div>
    @endsection