app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/post/{id}',['as'=>'home.post','uses'=>'AdminPostsController@post']);

Route::resource('admin/users','AdminUsersController');

Route::get('/admin',function (){
    return view('admin.index');
});

Route::get('/admin/create','AdminUsersController@create');

Route::group(['middleware'=>'admin'],function (){
    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCategoriesController');
    Route::resource('admin/media','AdminMediaController');
    //Route::resource('admin/media/store','AdminMediaController@store');
   // Route::get('admin/media/upload',['as'=>'admin.media.upload']);

    Route::resource('admin/comments','PostCommentsController');
    Route::resource('admin/comments/replies','CommentRepliesController');
});

Route::group(['middleware'=>'auth'],function (){
    Route::post('comment/reply','CommentRepliesController@createReply');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected  $fillable = [
        'name'
    ];
}

resources/views/admin/categories/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: pc3
 * Date: 12/19/2016
 * Time: 6:39 PM
 */

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h2>Categories Section</h2>

    <div class="col-sm-6">
        {!! Form::model($category,['method'=>'PATCH','action'=>['AdminCategoriesController@update',$category->id]]) !!}
        <div class="form-group">
            {!! Form::label('name','Category Name : ') !!}
            {!! Form::text('name',null,['class'=>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Update',['class'=>'btn btn-primary']) !!}
        </div>
        {!! Form::close() !!}
    </div>
    <div class="col-sm-6">
        {!! Form::open(['method'=>'DELETE','action'=>['AdminCategoriesController@destroy',$category->id]]) !!}
            {!! Form::submit('Delete',['class'=>'btn btn-danger']) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

    @section('content')
        <h2>Categories Section</h2>

        <div class="col-sm-6">
            {!! Form::open(['method'=>'POST','action'=>'AdminCategoriesController@store']) !!}
            <div class="form-group">
                {!! Form::label('name','Category Name : ') !!}
                {!! Form::text('name',null,['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('Create',['class'=>'btn btn-primary']) !!}
            </div>
            {!! Form::close() !!}
        </div>
        <div class="col-sm-6">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Created date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if($categories)
                        @foreach($categories as $category)
                            <tr>
                                <td>{{$category->id}}</td>
                                <td><a href="{{route('admin.categories.edit',$category->id)}}">{{$category->name}}</a></td>
                                <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'No date' }}</td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    @endsection